/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_lab2_Lab2 */

#ifndef _Included_org_example_lab2_Lab2
#define _Included_org_example_lab2_Lab2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_lab2_Lab2
 * Method:    bubbleSort
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_example_lab2_Lab2_bubbleSort
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_example_lab2_Lab2
 * Method:    insertionSort
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_example_lab2_Lab2_insertionSort
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_example_lab2_Lab2
 * Method:    selectionSort
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_example_lab2_Lab2_selectionSort
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_example_lab2_Lab2
 * Method:    shellSort
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_example_lab2_Lab2_shellSort
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_example_lab2_Lab2
 * Method:    mergeSort
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_example_lab2_Lab2_mergeSort
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
